version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: "yarn dev"
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app
  storybook:
    build:
      context: .
      dockerfile: Dockerfile
    command: "yarn storybook:docker"
    ports:
      - 6006:6006
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - NODE_ENV=development
