version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: "yarn dev"
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app
